#!/usr/bin/env bash

export CONTECO_LABEL="module.blank - ModEco"
export CONTECO_DESCRIPTION="The Modeco module template."

export CONTECO_TYPE="module"
export CONTECO_NAME="blank"
export CONTECO_TAG="v2.0.1"
export CONTECO_TAG_TYPE="incremental"

export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="modeco"
