#!/usr/bin/env bash

export CONTECO_LABEL="module.template - ModEco"
export CONTECO_DESCRIPTION="The Modeco module template."

export CONTECO_TYPE="module"
export CONTECO_NAME="template"
export CONTECO_TAG="v1.0.0"
export CONTECO_TAG_TYPE="incremental"

export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="modeco"
